# ATIVIDADE AULA 04

Objetivos da aula

*  Exercitar funcoes de agregação
*  Tratamento de dados
*  Formulação de hipóteses
*  Ordenação de dataFrames
*  Criação de colunas
    * Condicionais
    * Calculadas


O dataset que iremos utilizar para a análise desta aula está no link
https://github.com/techcomkathia/datasets/blob/main/resturante.csv

#PRIMEIRA ETAPA

Tratamento dos valores nulos e organização dos dados

### criar dataFrame

In [ ]:
import pandas as pd

In [ ]:
df= pd.read_csv("https://raw.githubusercontent.com/techcomkathia/datasets/main/resturante.csv", sep=";")
df

,conta,Unnamed: 1,gorjeta,sexo,area,dia_semana,horario,clientes,Unnamed: 8,nota,Atendente
0,207.5,NaN,2.45,F,interna,1.0,jantar,2.0,NaN,4.0,Milena
1,158.0,NaN,3.10,F,interna,5.0,almoco,2.0,NaN,4.0,Milena
2,343.0,NaN,6.70,M,externa,6.0,almoco,6.0,NaN,3.0,Mauricio
3,89.0,NaN,1.50,M,externa,4.0,almoco,2.0,NaN,4.0,Mauricio
4,126.9,NaN,2.00,M,interna,6.0,jantar,2.0,NaN,3.0,Mauricio
...,...,...,...,...,...,...,...,...,...,...,...
451,152.9,NaN,NaN,M,externa,4.0,jantar,3.0,NaN,5.0,Milena
452,149.7,NaN,3.00,F,externa,5.0,jantar,2.0,NaN,2.0,Mauricio
453,201.6,NaN,3.00,M,externa,2.0,jantar,2.0,NaN,4.0,Mauricio
454,172.9,NaN,2.71,M,externa,5.0,jantar,2.0,NaN,1.0,Mauricio
455,96.0,NaN,4.00,F,interna,3.0,jantar,2.0,NaN,2.0,Milena

### observar conjunto de dados antes do tratamento

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 456 entries, 0 to 455
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   conta       437 non-null    float64
 1   Unnamed: 1  0 non-null      float64
 2   gorjeta     419 non-null    float64
 3   sexo        437 non-null    object
 4   area        437 non-null    object
 5   dia_semana  437 non-null    float64
 6   horario     411 non-null    object
 7   clientes    437 non-null    float64
 8   Unnamed: 8  0 non-null      float64
 9    nota       437 non-null    float64
 10  Atendente   437 non-null    object
dtypes: float64(7), object(4)
memory usage: 39.3+ KB

### 1- Remover linhas nulas

In [ ]:
df.dropna(how='all', inplace= True)
df

,conta,Unnamed: 1,gorjeta,sexo,area,dia_semana,horario,clientes,Unnamed: 8,nota,Atendente
0,207.5,NaN,2.45,F,interna,1.0,jantar,2.0,NaN,4.0,Milena
1,158.0,NaN,3.10,F,interna,5.0,almoco,2.0,NaN,4.0,Milena
2,343.0,NaN,6.70,M,externa,6.0,almoco,6.0,NaN,3.0,Mauricio
3,89.0,NaN,1.50,M,externa,4.0,almoco,2.0,NaN,4.0,Mauricio
4,126.9,NaN,2.00,M,interna,6.0,jantar,2.0,NaN,3.0,Mauricio
...,...,...,...,...,...,...,...,...,...,...,...
451,152.9,NaN,NaN,M,externa,4.0,jantar,3.0,NaN,5.0,Milena
452,149.7,NaN,3.00,F,externa,5.0,jantar,2.0,NaN,2.0,Mauricio
453,201.6,NaN,3.00,M,externa,2.0,jantar,2.0,NaN,4.0,Mauricio
454,172.9,NaN,2.71,M,externa,5.0,jantar,2.0,NaN,1.0,Mauricio
455,96.0,NaN,4.00,F,interna,3.0,jantar,2.0,NaN,2.0,Milena

### 2- Remover colunas nulas

In [ ]:
df = df.dropna(axis=1, how="all")
df

,conta,gorjeta,sexo,area,dia_semana,horario,clientes,nota,Atendente
0,207.5,2.45,F,interna,1.0,jantar,2.0,4.0,Milena
1,158.0,3.10,F,interna,5.0,almoco,2.0,4.0,Milena
2,343.0,6.70,M,externa,6.0,almoco,6.0,3.0,Mauricio
3,89.0,1.50,M,externa,4.0,almoco,2.0,4.0,Mauricio
4,126.9,2.00,M,interna,6.0,jantar,2.0,3.0,Mauricio
...,...,...,...,...,...,...,...,...,...
451,152.9,NaN,M,externa,4.0,jantar,3.0,5.0,Milena
452,149.7,3.00,F,externa,5.0,jantar,2.0,2.0,Mauricio
453,201.6,3.00,M,externa,2.0,jantar,2.0,4.0,Mauricio
454,172.9,2.71,M,externa,5.0,jantar,2.0,1.0,Mauricio
455,96.0,4.00,F,interna,3.0,jantar,2.0,2.0,Milena

### 3- Ordenando o dataFrame por dias da semana

In [ ]:
df.sort_values(by='dia_semana', inplace=True)
df

<ipython-input-207-8da161132c51>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.sort_values(by='dia_semana', inplace=True)

,conta,gorjeta,sexo,area,dia_semana,horario,clientes,nota,Atendente
0,207.5,2.45,F,interna,1.0,jantar,2.0,4.0,Milena
327,233.3,5.65,M,externa,1.0,jantar,2.0,4.0,Luiza
326,346.5,3.68,M,externa,1.0,jantar,4.0,2.0,Luiza
325,85.7,2.00,M,externa,1.0,jantar,2.0,3.0,Milena
324,217.0,4.30,M,interna,1.0,jantar,2.0,1.0,Mauricio
...,...,...,...,...,...,...,...,...,...
143,177.8,3.27,M,interna,6.0,jantar,2.0,5.0,Beatriz
142,206.9,2.45,F,interna,6.0,jantar,4.0,5.0,Beatriz
141,150.6,3.00,F,interna,6.0,jantar,2.0,3.0,Beatriz
138,95.5,1.45,M,interna,6.0,jantar,2.0,5.0,Mauricio
234,186.0,3.21,F,externa,6.0,jantar,4.0,3.0,Milena

# SEGUNDA ETAPA

Conhecer os dados

### 4- Exiba as primeiras linhas do dataFrame

In [ ]:
df.head()

,conta,gorjeta,sexo,area,dia_semana,horario,clientes,nota,Atendente
0,207.5,2.45,F,interna,1.0,jantar,2.0,4.0,Milena
327,233.3,5.65,M,externa,1.0,jantar,2.0,4.0,Luiza
326,346.5,3.68,M,externa,1.0,jantar,4.0,2.0,Luiza
325,85.7,2.00,M,externa,1.0,jantar,2.0,3.0,Milena
324,217.0,4.30,M,interna,1.0,jantar,2.0,1.0,Mauricio

### 5- Exiba as 10 últimas linhas do dataFrame

In [ ]:
df.tail(10)

,conta,gorjeta,sexo,area,dia_semana,horario,clientes,nota,Atendente
148,312.7,5.00,M,interna,6.0,jantar,3.0,4.0,Mauricio
147,186.9,2.31,M,interna,6.0,jantar,3.0,4.0,Milena
146,169.3,3.07,F,interna,6.0,jantar,3.0,5.0,Beatriz
145,163.1,2.00,M,interna,6.0,NaN,3.0,4.0,Beatriz
144,240.6,NaN,M,interna,6.0,jantar,3.0,1.0,Beatriz
143,177.8,3.27,M,interna,6.0,jantar,2.0,5.0,Beatriz
142,206.9,2.45,F,interna,6.0,jantar,4.0,5.0,Beatriz
141,150.6,3.00,F,interna,6.0,jantar,2.0,3.0,Beatriz
138,95.5,1.45,M,interna,6.0,jantar,2.0,5.0,Mauricio
234,186.0,3.21,F,externa,6.0,jantar,4.0,3.0,Milena

###6- Exiba as principais medidas estatísticas para os dados numéricos

In [ ]:
df.describe()

             conta     gorjeta  dia_semana    clientes        nota
count   437.000000  419.000000  437.000000  437.000000  437.000000
mean    203.519908    3.002601    3.372998    2.485126    3.437071
std     141.053774    1.469542    2.168478    0.897439    1.304121
min      57.500000    1.000000    1.000000    1.000000    1.000000
25%     134.200000    2.000000    1.000000    2.000000    3.000000
50%     178.200000    3.000000    4.000000    2.000000    4.000000
75%     239.500000    3.500000    6.000000    3.000000    5.000000
max    2168.600000   15.000000    6.000000    6.000000    5.000000

### 7- Mostre as informações de tipos de dados, quantidade de valores não nulos e total de linhas para todas as colunas do dataframe

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 437 entries, 0 to 234
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   conta       437 non-null    float64
 1   gorjeta     419 non-null    float64
 2   sexo        437 non-null    object
 3   area        437 non-null    object
 4   dia_semana  437 non-null    float64
 5   horario     411 non-null    object
 6   clientes    437 non-null    float64
 7    nota       437 non-null    float64
 8   Atendente   437 non-null    object
dtypes: float64(5), object(4)
memory usage: 34.1+ KB

### 8- Crie um array com o nome de todas as colunas que agrupam nossos dados

In [ ]:
colunas = df.columns
colunas

Index(['conta', 'gorjeta', 'sexo', 'area', 'dia_semana', 'horario', 'clientes',
       ' nota', 'Atendente'],
      dtype='object')

### 9- Quantos atendentes trabalham no estabelecimento?

In [ ]:
atendentes = df['Atendente'].unique()
atendentes

array(['Milena', 'Luiza', 'Mauricio', 'Beatriz'], dtype=object)

# TERCEIRA ETAPA

Complementar as informações

###10- No arquivo cvs existe a coluna do valor da conta e a coluna do valor da gorjeta. Foi informado, que o valor dos 10% não está incluso no valor da conta.
No momento da extração dos dados não foi exportada a coluna que armazenava o valor da taxa de serviço. Considere 10% em cima do valor da conta. Crie uma coluna para armazenar esses dados

In [ ]:
df.insert(1,column= 'taxa_sevico',value=df['conta']*0.10)
df

,conta,taxa_sevico,gorjeta,sexo,area,dia_semana,horario,clientes,nota,Atendente
0,207.5,20.75,2.45,F,interna,1.0,jantar,2.0,4.0,Milena
327,233.3,23.33,5.65,M,externa,1.0,jantar,2.0,4.0,Luiza
326,346.5,34.65,3.68,M,externa,1.0,jantar,4.0,2.0,Luiza
325,85.7,8.57,2.00,M,externa,1.0,jantar,2.0,3.0,Milena
324,217.0,21.70,4.30,M,interna,1.0,jantar,2.0,1.0,Mauricio
...,...,...,...,...,...,...,...,...,...,...
143,177.8,17.78,3.27,M,interna,6.0,jantar,2.0,5.0,Beatriz
142,206.9,20.69,2.45,F,interna,6.0,jantar,4.0,5.0,Beatriz
141,150.6,15.06,3.00,F,interna,6.0,jantar,2.0,3.0,Beatriz
138,95.5,9.55,1.45,M,interna,6.0,jantar,2.0,5.0,Mauricio
234,186.0,18.60,3.21,F,externa,6.0,jantar,4.0,3.0,Milena

### 11- Crie uma coluna do total pago pelo clinte. Considere conta + 10% + gorjeta

In [ ]:
df.insert(3,column= 'total',value=df['conta']+df['gorjeta']+df['taxa_sevico'])
df

,conta,taxa_sevico,gorjeta,total,sexo,area,dia_semana,horario,clientes,nota,Atendente
0,207.5,20.75,2.45,230.70,F,interna,1.0,jantar,2.0,4.0,Milena
327,233.3,23.33,5.65,262.28,M,externa,1.0,jantar,2.0,4.0,Luiza
326,346.5,34.65,3.68,384.83,M,externa,1.0,jantar,4.0,2.0,Luiza
325,85.7,8.57,2.00,96.27,M,externa,1.0,jantar,2.0,3.0,Milena
324,217.0,21.70,4.30,243.00,M,interna,1.0,jantar,2.0,1.0,Mauricio
...,...,...,...,...,...,...,...,...,...,...,...
143,177.8,17.78,3.27,198.85,M,interna,6.0,jantar,2.0,5.0,Beatriz
142,206.9,20.69,2.45,230.04,F,interna,6.0,jantar,4.0,5.0,Beatriz
141,150.6,15.06,3.00,168.66,F,interna,6.0,jantar,2.0,3.0,Beatriz
138,95.5,9.55,1.45,106.50,M,interna,6.0,jantar,2.0,5.0,Mauricio
234,186.0,18.60,3.21,207.81,F,externa,6.0,jantar,4.0,3.0,Milena

### 12- Na coluna nota os clientes avaliam a experiência com o restaurante pontuando de 0 a 5.
Com base na tabela abaixo crie uma coluna para os novos parâmetros![image-asset.png]()

In [ ]:
def avaliacao(pontuacao):
    if pontuacao == 0:
        return 'muito insatisfeito'
    elif pontuacao == 1 or pontuacao ==2:
        return 'pouco insatisfeito'
    elif pontuacao == 3:
        return 'neutro'
    elif pontuacao == 4:
        return 'pouco satisfeito'
    elif pontuacao == 5:
        return 'muito satisfeito'
    else:
        return 'não classificado'

In [ ]:
condicao = lambda nota: 'muito insatisfeito' if (nota<1.0) else (#\
        'pouco insatisfeito' if (nota<=2.0) else ('neutro' if (nota<4.0)
         else ('pouco insatisfeito' if (nota<5.0) else 'muito satisfeito')))

In [ ]:
df

,conta,taxa_sevico,gorjeta,total,sexo,area,dia_semana,horario,clientes,nota,Atendente
0,207.5,20.75,2.45,230.70,F,interna,1.0,jantar,2.0,4.0,Milena
327,233.3,23.33,5.65,262.28,M,externa,1.0,jantar,2.0,4.0,Luiza
326,346.5,34.65,3.68,384.83,M,externa,1.0,jantar,4.0,2.0,Luiza
325,85.7,8.57,2.00,96.27,M,externa,1.0,jantar,2.0,3.0,Milena
324,217.0,21.70,4.30,243.00,M,interna,1.0,jantar,2.0,1.0,Mauricio
...,...,...,...,...,...,...,...,...,...,...,...
143,177.8,17.78,3.27,198.85,M,interna,6.0,jantar,2.0,5.0,Beatriz
142,206.9,20.69,2.45,230.04,F,interna,6.0,jantar,4.0,5.0,Beatriz
141,150.6,15.06,3.00,168.66,F,interna,6.0,jantar,2.0,3.0,Beatriz
138,95.5,9.55,1.45,106.50,M,interna,6.0,jantar,2.0,5.0,Mauricio
234,186.0,18.60,3.21,207.81,F,externa,6.0,jantar,4.0,3.0,Milena

In [ ]:
df.columns

Index(['conta', 'taxa_sevico', 'gorjeta', 'total', 'sexo', 'area',
       'dia_semana', 'horario', 'clientes', ' nota', 'Atendente'],
      dtype='object')

In [ ]:
df['avaliacao'] = df[' nota'].map(condicao)
df

<ipython-input-220-c41c283ee956>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['avaliacao'] = df[' nota'].map(condicao)

,conta,taxa_sevico,gorjeta,total,sexo,area,dia_semana,horario,clientes,nota,Atendente,avaliacao
0,207.5,20.75,2.45,230.70,F,interna,1.0,jantar,2.0,4.0,Milena,pouco insatisfeito
327,233.3,23.33,5.65,262.28,M,externa,1.0,jantar,2.0,4.0,Luiza,pouco insatisfeito
326,346.5,34.65,3.68,384.83,M,externa,1.0,jantar,4.0,2.0,Luiza,pouco insatisfeito
325,85.7,8.57,2.00,96.27,M,externa,1.0,jantar,2.0,3.0,Milena,neutro
324,217.0,21.70,4.30,243.00,M,interna,1.0,jantar,2.0,1.0,Mauricio,pouco insatisfeito
...,...,...,...,...,...,...,...,...,...,...,...,...
143,177.8,17.78,3.27,198.85,M,interna,6.0,jantar,2.0,5.0,Beatriz,muito satisfeito
142,206.9,20.69,2.45,230.04,F,interna,6.0,jantar,4.0,5.0,Beatriz,muito satisfeito
141,150.6,15.06,3.00,168.66,F,interna,6.0,jantar,2.0,3.0,Beatriz,neutro
138,95.5,9.55,1.45,106.50,M,interna,6.0,jantar,2.0,5.0,Mauricio,muito satisfeito
234,186.0,18.60,3.21,207.81,F,externa,6.0,jantar,4.0,3.0,Milena,neutro

### 13- Os dias da semana estão numerados. Sendo 1 o domingo e 7 o sábado. Crie uma coluna com o nome dos dias da semana

In [ ]:
condicao =  {1: 'Domingo', 2: 'Segunda', 3: 'Terça', 4: 'Quarta', 5: 'Quinta', 6: 'Sexta', 7: 'Sábado'}
df['nome_dia']= df['dia_semana'].map(condicao)
df

<ipython-input-221-13437b35c4b2>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['nome_dia']= df['dia_semana'].map(condicao)

,conta,taxa_sevico,gorjeta,total,sexo,area,dia_semana,horario,clientes,nota,Atendente,avaliacao,nome_dia
0,207.5,20.75,2.45,230.70,F,interna,1.0,jantar,2.0,4.0,Milena,pouco insatisfeito,Domingo
327,233.3,23.33,5.65,262.28,M,externa,1.0,jantar,2.0,4.0,Luiza,pouco insatisfeito,Domingo
326,346.5,34.65,3.68,384.83,M,externa,1.0,jantar,4.0,2.0,Luiza,pouco insatisfeito,Domingo
325,85.7,8.57,2.00,96.27,M,externa,1.0,jantar,2.0,3.0,Milena,neutro,Domingo
324,217.0,21.70,4.30,243.00,M,interna,1.0,jantar,2.0,1.0,Mauricio,pouco insatisfeito,Domingo
...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,177.8,17.78,3.27,198.85,M,interna,6.0,jantar,2.0,5.0,Beatriz,muito satisfeito,Sexta
142,206.9,20.69,2.45,230.04,F,interna,6.0,jantar,4.0,5.0,Beatriz,muito satisfeito,Sexta
141,150.6,15.06,3.00,168.66,F,interna,6.0,jantar,2.0,3.0,Beatriz,neutro,Sexta
138,95.5,9.55,1.45,106.50,M,interna,6.0,jantar,2.0,5.0,Mauricio,muito satisfeito,Sexta
234,186.0,18.60,3.21,207.81,F,externa,6.0,jantar,4.0,3.0,Milena,neutro,Sexta

# QUARTA ETAPA
Respondendo aos questionamentos

### 13- Quantos atendimentos foram feitos em cada dia da semana

In [ ]:
df['nome_dia'].value_counts()

Domingo    171
Sexta      117
Quinta      80
Segunda     30
Quarta      24
Terça       15
Name: nome_dia, dtype: int64

### 14- Existe uma predileção por alguma área?

In [ ]:
df['area'].value_counts()

interna    220
externa    217
Name: area, dtype: int64

### 15- Quanto foi o faturamento total do restaurante no período analizado?

In [ ]:
round(df['conta'].sum(), 2)

88938.2

###16- Qual foi a maior gorjeta recebida por Milena?

In [ ]:
condicao = df['Atendente'] == 'Milena'
gorjetas_milena = df[condicao]['gorjeta']
gorjetas_milena.max()

15.0

### 17- Quantos clientes foram atendidos por cada um dos colaboradores nas sextas?

In [ ]:
df

,conta,taxa_sevico,gorjeta,total,sexo,area,dia_semana,horario,clientes,nota,Atendente,avaliacao,nome_dia
0,207.5,20.75,2.45,230.70,F,interna,1.0,jantar,2.0,4.0,Milena,pouco insatisfeito,Domingo
327,233.3,23.33,5.65,262.28,M,externa,1.0,jantar,2.0,4.0,Luiza,pouco insatisfeito,Domingo
326,346.5,34.65,3.68,384.83,M,externa,1.0,jantar,4.0,2.0,Luiza,pouco insatisfeito,Domingo
325,85.7,8.57,2.00,96.27,M,externa,1.0,jantar,2.0,3.0,Milena,neutro,Domingo
324,217.0,21.70,4.30,243.00,M,interna,1.0,jantar,2.0,1.0,Mauricio,pouco insatisfeito,Domingo
...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,177.8,17.78,3.27,198.85,M,interna,6.0,jantar,2.0,5.0,Beatriz,muito satisfeito,Sexta
142,206.9,20.69,2.45,230.04,F,interna,6.0,jantar,4.0,5.0,Beatriz,muito satisfeito,Sexta
141,150.6,15.06,3.00,168.66,F,interna,6.0,jantar,2.0,3.0,Beatriz,neutro,Sexta
138,95.5,9.55,1.45,106.50,M,interna,6.0,jantar,2.0,5.0,Mauricio,muito satisfeito,Sexta
234,186.0,18.60,3.21,207.81,F,externa,6.0,jantar,4.0,3.0,Milena,neutro,Sexta

In [ ]:
condicao = df['nome_dia'] == 'Sexta'
df[condicao]['Atendente'].value_counts()

Beatriz     36
Mauricio    30
Milena      29
Luiza       22
Name: Atendente, dtype: int64

###18- Quantos clientes ficaram muito insatisfeito ou pouco insatisfeito com o atendimento do Mauricio?

In [ ]:
condicao = df['Atendente']== 'Mauricio'

df[condicao]

,conta,taxa_sevico,gorjeta,total,sexo,area,dia_semana,horario,clientes,nota,Atendente,avaliacao,nome_dia
324,217.0,21.70,4.30,243.00,M,interna,1.0,jantar,2.0,1.0,Mauricio,pouco insatisfeito,Domingo
319,240.6,24.06,3.60,268.26,M,externa,1.0,jantar,3.0,2.0,Mauricio,pouco insatisfeito,Domingo
317,96.0,9.60,4.00,109.60,F,externa,1.0,jantar,2.0,3.0,Mauricio,neutro,Domingo
155,222.3,22.23,5.00,249.53,M,interna,1.0,jantar,2.0,5.0,Mauricio,muito satisfeito,Domingo
156,324.0,32.40,6.00,362.40,M,interna,1.0,jantar,4.0,5.0,Mauricio,muito satisfeito,Domingo
...,...,...,...,...,...,...,...,...,...,...,...,...,...
367,265.9,26.59,3.41,295.90,M,externa,6.0,jantar,3.0,3.0,Mauricio,neutro,Sexta
169,202.9,20.29,3.21,226.40,M,externa,6.0,jantar,2.0,4.0,Mauricio,pouco insatisfeito,Sexta
165,380.1,38.01,3.00,421.11,M,externa,6.0,jantar,4.0,1.0,Mauricio,pouco insatisfeito,Sexta
148,312.7,31.27,5.00,348.97,M,interna,6.0,jantar,3.0,4.0,Mauricio,pouco insatisfeito,Sexta
138,95.5,9.55,1.45,106.50,M,interna,6.0,jantar,2.0,5.0,Mauricio,muito satisfeito,Sexta

In [ ]:
df[condicao]['avaliacao'].value_counts()

pouco insatisfeito    55
neutro                37
muito satisfeito      29
Name: avaliacao, dtype: int64

‘line’ : Gráfico de Linhas
‘bar’ : Gráfico de Barras
‘barh’ : Gráfico de Barras Horizontais
‘hist’ : Histograma
‘box’ : Boxplot
‘kde’ : Kernel Density Estimation plot
‘density’ : Mesmo que ‘kde’
‘area’ : Gráfico de Área
‘pie’ : Gráfico de Pizza
‘scatter’ : Gráfico de Dispersão
‘hexbin’ : Gráfico de Dispersão Hexadecimal